### ISSUE TITLE
After install of  autotrace_0.40.0-20190108_all.deb in Ubuntu 18.04 I got libMagickCore-6.Q16.so.2 Error

### ISSUE THREAD

**Issue by Acer54** [autotrace/autotrace#19] opened 2019-01-23 22:31 UTC
Fresh installation of deb-package leads into error message:
```
matthias@matthias-tuxedo:~/Downloads$ sudo apt install ./autotrace_0.40.0-20190108_all.deb 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Hinweis: »autotrace« wird an Stelle von »./autotrace_0.40.0-20190108_all.deb« gewählt.
Die folgenden NEUEN Pakete werden installiert:
  autotrace
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 16 nicht aktualisiert.
Es müssen noch 0 B von 410 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 2.179 kB Plattenplatz zusätzlich benutzt.
Holen:1 /home/matthias/Downloads/autotrace_0.40.0-20190108_all.deb autotrace all 0.40.0-20190108 [410 kB]
Vormals nicht ausgewähltes Paket autotrace wird gewählt.
(Lese Datenbank ... 284035 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../autotrace_0.40.0-20190108_all.deb ...
Entpacken von autotrace (0.40.0-20190108) ...
Trigger für man-db (2.8.3-2ubuntu0.1) werden verarbeitet ...
autotrace (0.40.0-20190108) wird eingerichtet ...
matthias@matthias-tuxedo:~/Downloads$ autotrace 
autotrace: error while loading shared libraries: libMagickCore-6.Q16.so.2: cannot open shared object file: No such file or directory
```
Have I missed something?

**Comment by iszotic** [comment] 2019-03-07 15:34
In Ubuntu 18.04 (at least in my system) there's only libMagickCore-6.Q16.so.3, so coping one of the link files and rename it to libMagickCore-6.Q16.so.2 fixed the issue, later it happened the same with libpng12.so.0, and there's libpng16.so.0, so I did the same and rename one of the link files to libpng12.so.0.
I tested the functionality with https://github.com/fablabnbg/inkscape-centerline-trace, no bugs whatsoever
these libraries are located in /usr/lib/x86_64-linux-gnu/

**Comment by jnweiger** [comment] 2019-03-12 21:05
When actually building a deb package on ubuntu-18.04 all looks good.
@iszotic seems to be right, not all Ubuntu have the same library versions, so there is no one-fit-all deb package :-)

ldd /usr/bin/autotrace  | grep Core
	libMagickCore-6.Q16.so.3 => /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.3 (0x00007f191efe0000)


[autotrace_0.40.0-20190312_ubuntu1804.deb.zip](https://github.com/autotrace/autotrace/files/2958787/autotrace_0.40.0-20190312_ubuntu1804.deb.zip)

**Comment by lemenkov** [comment] 2019-03-29 13:07
Duplicate of the #12 issue.

**Closed by lemenkov** 2019-03-29 13:07 UTC

**Comment by jnweiger** [comment] 2019-03-29 14:35
any hints, how we could relax the dependencies at runtime welcome.
Currently runtime seems to ask for exactly what was used at buildtime. That
is overspecific in many cases.
