### ISSUE TITLE
make fails - png.h not found

### ISSUE THREAD

**Issue by exekutive** [autotrace/autotrace#111] opened 2023-09-16 07:09 UTC
M2 Mac, OS 13.5.2

```

src/input-gf.c:319:44: warning: implicit conversion from 'int' to 'char' changes value from 255 to -1 [-Wconstant-conversion]
          PIXEL(sym, matrix_y, matrix_x) = 255;
                                         ~ ^~~
1 warning generated.
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/opt/homebrew/Cellar/graphicsmagick/1.3.41_1/include/GraphicsMagick -I/opt/homebrew/Cellar/pstoedit/3.78/include -I/opt/homebrew/Cellar/glib/2.78.0/include -I/opt/homebrew/Cellar/glib/2.78.0/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.78.0/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.42/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi -DLOCALEDIR=\"/usr/local/share/locale\" -g -O2 -c src/input-gf.c -o src/input-gf.o >/dev/null 2>&1
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/opt/homebrew/Cellar/graphicsmagick/1.3.41_1/include/GraphicsMagick -I/opt/homebrew/Cellar/pstoedit/3.78/include  -I/opt/homebrew/Cellar/glib/2.78.0/include -I/opt/homebrew/Cellar/glib/2.78.0/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.78.0/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.42/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi -DLOCALEDIR=\""/usr/local/share/locale"\"   -g -O2 -c -o src/input-png.lo src/input-png.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/opt/homebrew/Cellar/graphicsmagick/1.3.41_1/include/GraphicsMagick -I/opt/homebrew/Cellar/pstoedit/3.78/include -I/opt/homebrew/Cellar/glib/2.78.0/include -I/opt/homebrew/Cellar/glib/2.78.0/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.78.0/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/pcre2/10.42/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/ffi -DLOCALEDIR=\"/usr/local/share/locale\" -g -O2 -c src/input-png.c  -fno-common -DPIC -o src/.libs/input-png.o
src/input-png.c:32:10: fatal error: 'png.h' file not found
#include <png.h>
         ^~~~~~~
1 error generated.
make[2]: *** [src/input-png.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

libpng is installed

```
==> libpng: stable 1.6.40 (bottled), HEAD
Library for manipulating PNG images
http://www.libpng.org/pub/png/libpng.html
/opt/homebrew/Cellar/libpng/1.6.40 (27 files, 1.3MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-06-26 at 14:02:13
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lib/libpng.rb
License: libpng-2.0

```

**Comment by exekutive** [comment] 2023-09-16 07:38
solution is to export
```
CPATH=/opt/homebrew/include
LIBRARY_PATH=/opt/homebrew/lib
```
environment variables

**Comment by lemenkov** [comment] 2023-11-24 21:54
Looks to me like something specific to that particular installation. Normally I'd expetc the package to be available after the installation with any package manager.

**Comment by exekutive** [comment] 2023-11-25 06:00
any GOOD package manager

**Comment by lemenkov** [comment] 2024-02-21 23:23
I've improved building instructions of OS X so I am going to close it. Also take a loo at [OS X test workflow](https://github.com/autotrace/autotrace/blob/master/.github/workflows/macosx_test.yml).

**Closed by lemenkov** 2024-02-21 23:23 UTC

**Comment by ryandesign** [comment] 2024-04-05 00:10
Please reopen. This problem should not be happening if autotrace were using pkg-config correctly to find libpng.

I think the problem is here:

https://github.com/autotrace/autotrace/blob/cba2237e379ab82d4c0c5d1ec86f7b69732c162f/Makefile.am#L144

`LIBPNG_CFLAGS` is missing in this list of variables.
