### ISSUE TITLE
Empty output on macos

### ISSUE THREAD

**Issue by erikparr** [autotrace/autotrace#53] opened 2021-11-29 10:58 UTC
Empty output with zero file size on macos 11.5.2. Bmp to svg. Tried with different settings and files. Nothing working.

**Comment by lemenkov** [comment] 2022-04-26 17:11
That's very strange since we have tests which do almost exactly this (png to svg). Are permissions ok?

**Comment by lemenkov** [comment] 2022-05-31 17:13
Going to close this one. We do have a running test for Mac OS X which converts BMP to SVG.  If you have a reproducer then please open a new ticket

**Closed by lemenkov** 2022-05-31 17:13 UTC
